version: '3.8'

services:
  app:
    image: jdagon2000/withus-cmc
    container_name: withus-app
    env_file:
      - ./.env
    expose:
      - "8080"
    volumes:
      - ./logs:/app/logs
      - ./config/firebase-key.json:/app/config/firebase-key.json:ro
    networks:
      - withus-network
    restart: no

  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - withus-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # crontab으로 매일 3시 인증서 갱신 후 nginx 재시작
    networks:
      - withus-network

networks:
  withus-network:
    driver: bridge
