events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    # 1. HTTP 접속 시 HTTPS로 강제 리다이렉트
    server {
        listen 80;
        server_name withus.p-e.kr;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # 2. HTTPS 설정
    server {
        listen 443 ssl;
        server_name withus.p-e.kr;

        # 인증서 파일 경로 (Certbot이 생성한 위치)
        ssl_certificate /etc/letsencrypt/live/withus.p-e.kr/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/withus.p-e.kr/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        location / {
            set $backend_url http://withus-app:8080;

            proxy_pass $backend_url;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port 443;
        }
    }
}
